### ISSUE TITLE
AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateTokenWithIAM operation:

### ISSUE THREAD

**Issue by justmekaren** [aws-samples/custom-web-experience-with-amazon-q-business#16]
We are getting this error for some users. But other user can login without issues.

File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)File "/opt/custom-web-experience-with-amazon-q-business/src/app.py", line 37, in <module>
    st.session_state["idc_jwt_token"] = utils.get_iam_oidc_token(st.session_state.token["id_token"])
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/opt/custom-web-experience-with-amazon-q-business/src/utils.py", line 72, in get_iam_oidc_token
    response = client.create_token_with_iam(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by ennio1991** [comment]
@justmekaren are there differences in terms of IAM groups, roles and permissions among the different users?

**Comment by justmekaren** [comment]
I dont think there is a difference, we used the IAM IDC is the org level and controlled the access in cognito in the account level. As far as I understand it would always assume the IAM role assigned to the application.

**Comment by ennio1991** [comment]
I am wondering if you have any defined Service control policies at the AWS Organizations level that explicitly denies the sso-oauth:CreateTokenWithIAM action, or some permission set defined for or more specific IAM Identity Center groups.

**Comment by j2clerck** [comment]
Hello @justmekaren, this error can happen if the user trying to connect is not assigned to the **customer managed application** that you created in IAM Identity Center.
The options to solve this are either to switch the customer managed application that you created to not require assignments and allowing every authenticated user to exchange token 
![image](https://github.com/aws-samples/custom-web-experience-with-amazon-q-business/assets/8290156/af3351b5-ad6b-41e6-b81c-b2780bd01d37)
or you should assign users to the customer managed application.
![image](https://github.com/aws-samples/custom-web-experience-with-amazon-q-business/assets/8290156/b8687be4-f781-42b8-b0f9-f66670d6c0ec)
Let me know if this solves the issue.

**Comment by justmekaren** [comment]
Thank you this resolves the issue now.

**Comment by justmekaren** [comment]
I realized another issue came up.

AccessDeniedException: An error occurred (AccessDeniedException) when calling the ChatSync operation: User is not authorized for this service call.
Traceback:
File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/opt/custom-web-experience-with-amazon-q-business/src/app.py", line 118, in <module>
    response = utils.get_queue_chain(prompt,st.session_state["conversationId"],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/custom-web-experience-with-amazon-q-business/src/utils.py", line 135, in get_queue_chain
    answer = amazon_q.chat_sync(
             ^^^^^^^^^^^^^^^^^^^
File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/custom-web-experience-with-amazon-q-business/venv/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by j2clerck** [comment]
@justmekaren This usually means that the user trying to access Q is not subscribed in the Q business app.
However we've also just fixed an issue where credentials would outlast the current app session which could lead to this error if you tried once to use Q and then subscribed. Could you try to redeploy the EC2 instance (just terminate it and the autoscaling group will create a new) and confirm if you have still the error ?

**Comment by justmekaren** [comment]
But the user who was getting the error was already subscribed. Does that mean that all user must subscribe to Q app before they can fully use it?

**Comment by j2clerck** [comment]
Hi

Did you try to redeploy the EC2 instance as I suggested ?
If you still encounter the issue, can you try to use the native UI of Q
(through IAM Identity Center) to confirm that Q is working correctly ?

Regards,
Joseph

Le lun. 24 juin 2024 à 14:48, justmekaren ***@***.***> a
écrit :

**Comment by justmekaren** [comment]
Yes, I did redeploy it and working as expected at the moment.
