### ISSUE TITLE
Step 2: Create an IAM Identity Center Application - For Application type, select OAuth 2.0, then choose Next. options can't found in my aws console 

### ISSUE THREAD

**Issue by bcshmily** [aws-samples/custom-web-experience-with-amazon-q-business#20]
Step 2: Create an IAM Identity Center Application - For Application type, select OAuth 2.0, then choose Next.
options can't found in my aws console

**Comment by ennio1991** [comment]
If you can't find the option of creating a new custom managed application, please Enable Organizations with IAM Identity Center https://docs.aws.amazon.com/singlesignon/latest/userguide/get-set-up-for-idc.html
